// new_files/cicero-react/src/components/footer/Footer.jsx
import { useContext } from "react";
import { Link } from "react-router-dom";
import ContainerWrapper from "../common/ContainerWrapper";
import ReavealAnimationProvider from "../common/revealAnimation/ReavealAnimationProvider";
import { LanguageContext } from "../../contexts/LanguageContext";
import { enTranslations } from "../../translations/en";
import { ptTranslations } from "../../translations/pt";

const Footer = () => {
    const { language } = useContext(LanguageContext);
    const translations = language === 'pt' ? ptTranslations : enTranslations;

    return (
        <footer className="pt-[50px] pb-[30px] bg-[var(--background)]">
            <ContainerWrapper>
                <hr className="mb-[30px] h-[1px] w-full border-none bg-[var(--foreground)] opacity-20" />
                <ReavealAnimationProvider topOrBottm={100}>
                    <div className="flex flex-col">
                        <div className="flex flex-col md:flex-row items-start gap-[15px] md:gap-16">
                            <ul>
                                <li className="font-Inter hover:scale-105 transition-all mb-4 text-base font-semibold uppercase leading-[20px] text-[var(--foreground)]">
                                    <Link to="#">{translations.footer.aboutUs}</Link>
                                </li>
                                <li className="font-Inter hover:scale-105 transition-all mb-4 text-base font-semibold uppercase leading-[20px] text-[var(--foreground)]">
                                    <Link to="https://blog.synthetic.lawyer" target="_blank">{translations.footer.blog}</Link>
                                </li>
                                <li className="font-Inter hover:scale-105 text-base font-semibold uppercase leading-[20px] text-[var(--foreground)]">
                                    <Link to="#">{translations.footer.cookieSettings}</Link>
                                </li>
                            </ul>
                            <ul>
                                <li className="font-Inter hover:scale-105 transition-all mb-4 text-base font-semibold uppercase leading-[20px] text-[var(--foreground)]">
                                    <Link to="mailto:contact@cicero.chat">{translations.footer.contactUs}</Link>
                                </li>
                                <li className="font-Inter hover:scale-105 transition-all mb-4 text-base font-semibold uppercase leading-[20px] text-[var(--foreground)]">
                                    <Link to="https://www.linkedin.com/company/cicero-contracts" target="_blank">LinkedIn</Link>
                                </li>
                                <li className="font-Inter hover:scale-105 text-base font-semibold uppercase leading-[20px] text-[var(--foreground)]">
                                    <Link to="#">{translations.footer.termsPrivacy}</Link>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <hr className="mt-[30px] h-[1px] w-full border-none bg-[var(--foreground)] opacity-20" />

                    <div className="flex flex-col md:flex-row items-center justify-between mt-[30px] w-full">
                        <div className="logo">
                            <h1 className="font-Inter font-bold text-[2.7rem] tracking-tight text-[var(--foreground)]">CICERO</h1>
                        </div>
                    </div>
                </ReavealAnimationProvider>
            </ContainerWrapper>
        </footer>
    );
};

export default Footer;

// src/lib/components/landing/Footer.svelte
<script lang="ts">
    import { t } from '$lib/landing/translations';
</script>

<footer class="w-full py-12 bg-[var(--background)]">
    <div class="w-full max-w-[1440px] mx-auto px-4">
        <div class="flex flex-col items-center gap-8">
            <!-- CICERO Logo with same styling as navbar -->
            <div class="font-ClashDisplay px-6 py-2 rounded-md flex items-center justify-center bg-[var(--surface-primary)]">
                <h1 class="text-[var(--text-primary)] text-[2.7rem] font-ClashDisplay font-semibold tracking-tight">
                    CICERO
                </h1>
            </div>

            <!-- Links -->
            <div class="flex flex-col md:flex-row gap-8">
                <a href="/about" class="text-[var(--foreground)] hover:opacity-80 transition-opacity">
                    {$t('footer.aboutUs')}
                </a>
                <a href="https://blog.synthetic.lawyer" target="_blank" class="text-[var(--foreground)] hover:opacity-80 transition-opacity">
                    {$t('footer.blog')}
                </a>
                <a href="mailto:contact@cicero.chat" class="text-[var(--foreground)] hover:opacity-80 transition-opacity">
                    {$t('footer.contactUs')}
                </a>
                <a href="https://www.cicero.chat/tos.html" class="text-[var(--foreground)] hover:opacity-80 transition-opacity">
                    {$t('footer.termsPrivacy')}
                </a>
                <a href="https://www.cicero.chat/privacy-policy.html" class="text-[var(--foreground)] hover:opacity-80 transition-opacity">
                    Privacy Policy
                </a>
            </div>

            <!-- Copyright -->
            <div class="text-[var(--foreground)] opacity-60">
                © 2024 Cicero. {$t('footer.rights')}
            </div>
        </div>
    </div>
</footer>

<style>
    @font-face {
        font-family: 'ClashDisplay';
        src: url('/assets/fonts/Inter-SemiBold.woff2') format('woff2');
        font-weight: 400;
        font-style: normal;
        font-display: swap;
    }

    @font-face {
        font-family: 'ClashDisplay';
        src: url('/assets/fonts/Inter-SemiBold.woff2') format('woff2');
        font-weight: 600;
        font-style: normal;
        font-display: swap;
    }
</style>
