// new_files/landing/FaqSection.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import gsap from 'gsap';
    import { t, currentLang } from '$lib/landing/translations';

    let openIndex = -1;
    let sectionRef: HTMLElement;
    let headingRef: HTMLElement;
    let translate: (key: string) => string;

    // Subscribe to the derived store
    $: translate = $t;

    const questions = [
        { q: 'faq.q1', a: 'faq.a1' },
        { q: 'faq.q2', a: 'faq.a2' },
        { q: 'faq.q3', a: 'faq.a3' },
        { q: 'faq.q4', a: 'faq.a4' }
    ];

    function toggleAccordion(index: number) {
        openIndex = openIndex === index ? -1 : index;
    }

    onMount(() => {
        if (!sectionRef || !headingRef) return;

        gsap.from(headingRef, {
            y: 50,
            opacity: 0,
            scrollTrigger: {
                trigger: headingRef,
                start: "top 80%",
                end: "top 60%",
                scrub: true
            }
        });

        const items = sectionRef.querySelectorAll('.faq-item');
        items.forEach((item, index) => {
            gsap.from(item, {
                x: index % 2 === 0 ? -50 : 50,
                opacity: 0,
                scrollTrigger: {
                    trigger: item,
                    start: "top 80%",
                    end: "top 60%",
                    scrub: true
                }
            });
        });
    });
</script>

<section bind:this={sectionRef} class="py-16 bg-[var(--background)]">
    <div class="container mx-auto px-4 max-w-[1440px]">
        <div bind:this={headingRef}>
            <h2 class="text-4xl md:text-5xl font-['Inter'] font-semibold text-center mb-16 text-[var(--foreground)]">
                {translate('faq.title')}
            </h2>
        </div>

        <div class="grid md:grid-cols-2 gap-8">
            {#each questions as { q, a }, index}
                <button
                    class="faq-item w-full text-left p-6 bg-[var(--surface-primary)] text-[var(--text-primary)] rounded-lg shadow-sm hover:shadow-md transition-all duration-200"
                    on:click={() => toggleAccordion(index)}
                    aria-expanded={openIndex === index}
                >
                    <div class="flex justify-between items-center">
                        <h3 class="text-xl font-semibold">
                            {translate(q)}
                        </h3>
                        <svg
                            class="w-6 h-6 transform transition-transform duration-200 {openIndex === index ? 'rotate-180' : ''}"
                            fill="none"
                            stroke="currentColor"
                            viewBox="0 0 24 24"
                        >
                            <path
                                stroke-linecap="round"
                                stroke-linejoin="round"
                                stroke-width="2"
                                d="M19 9l-7 7-7-7"
                            />
                        </svg>
                    </div>
                    {#if openIndex === index}
                        <p class="mt-4 opacity-80">
                            {translate(a)}
                        </p>
                    {/if}
                </button>
            {/each}
        </div>
    </div>
</section>

// new_files/cicero-react/src/components/fAqSection/FaQSection.jsx
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { useRef } from "react";
import { useLanguage } from "../../contexts/LanguageContext.jsx";
import Accordion from "../common/accordion/Accordion";
import ContainerWrapper from "../common/ContainerWrapper";

const FaQSection = () => {
    const headingRef = useRef(null);
    const sectionRef = useRef(null);
    const { translations } = useLanguage();

    useGSAP(() => {
        gsap.to(sectionRef.current, {
            yPercent: -100,
            opacity: 0,
            scrollTrigger: {
                trigger: sectionRef.current,
                scroller: "body",
                scrub: 1,
                start: "top 20%",
                end: "top -20%",
            },
        });

        gsap.from(headingRef.current, {
            scale: 0,
            opacity: 0,
            scrollTrigger: {
                trigger: ".faqSection",
                scroller: "body",
                scrub: true,
                end: "top 100%",
            },
        });
    }, []);

    const halfLength = Math.ceil(translations.faq.questions.length / 2);
    const firstColumn = translations.faq.questions.slice(0, halfLength);
    const secondColumn = translations.faq.questions.slice(halfLength);

    return (
        <section ref={sectionRef} className="faqSection py-16 bg-[var(--background)]">
            <ContainerWrapper>
                <div ref={headingRef}>
                    <h2 className="text-4xl md:text-5xl font-['Inter'] font-semibold text-center mb-16 text-[var(--foreground)]">
                        {translations.faq.title}
                    </h2>
                </div>

                <div className="mt-[50px]">
                    <div className="grid md:grid-cols-2 gap-8">
                        <div className="flex flex-col gap-5">
                            {firstColumn.map((question, index) => (
                                <Accordion key={index} question={question} />
                            ))}
                        </div>
                        <div className="flex flex-col gap-5">
                            {secondColumn.map((question, index) => (
                                <Accordion key={index + halfLength} question={question} />
                            ))}
                        </div>
                    </div>
                </div>

                <div className="flex justify-center mt-16">
                    <button className="try-it-now-btn bg-[var(--surface-primary)] text-[var(--text-primary)] hover:bg-gradient-to-r hover:from-[var(--red-light)] hover:to-[var(--red-dark)] hover:text-white px-[25px] py-[15px] font-sans text-[1rem] font-medium leading-[20px] rounded-full uppercase transition-all duration-300">
                        {translations.hero.cta}
                    </button>
                </div>
            </ContainerWrapper>
        </section>
    );
};

export default FaQSection;
